### PR TITLE
remove dynamic polynomials.  fixes #176 

### LINKED ISSUE #176: Remove use of DynamicPolynomials
Replace with MTK / Symbolics.jl

### PR DESCRIPTION
**Pull request by lucaferranti**
Removed tests with DynamicPolynomials, and updated Project.toml. Should fix #176

### CODE REVIEW

**Comment by lucaferranti** [comment]
The test causing problems is
```
    a = 3
    S4 = @constraint x^2 + y^2 - $a <= 0
    paving = pave(S4, X)
 ```
with error `UndefVarError: a not defined` . The failure is only on nightly, it works on 1.4 (and on 1.5, tested on my machine). What should we do with this?

**Comment by lucaferranti** [comment]
@dpsanders allowing failure on nightly (the other packages in juliaintervals allow it too) it seems to work. I think this is starting to look ready, what do you think?

**Comment by dpsanders** [comment]
Rather than just removing those tests can they be replaced with tests using ModelingToolkit variables? Or are. There similar tests already?

**Comment by lucaferranti** [comment]
yes, there seem to be a couple of tests using MTK with Separator [here](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/blob/master/test/runtests.jl#L109-L134) and with Contractor [here](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/blob/master/test/runtests.jl#L44-L82)

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
